### ISSUE TITLE
not work on production

### ISSUE THREAD

**Issue by nutthapol-jr** [alexus37/react-google-streetview#1] opened 2019-10-30 16:48 UTC
TypeError: Super expression must either be null or a function
<img width="396" alt="Screen Shot 2562-10-30 at 23 47 00" src="https://user-images.githubusercontent.com/50816442/67879588-cfef0300-fb6f-11e9-9874-b3ea415468d5.png">

**Comment by alexus37** [comment] 2019-10-30 17:03
Thanks for reporting. Could you please elaborate what you mean with on  production? I can look into it on Monday.

**Comment by alexus37** [comment] 2019-11-04 10:27
You can build the app with production mode by running `npm run docs`, which creates a standalone in the docs folder. If I open this I don't get the TypeError. Could you please provide detailed reproduction steps.

**Comment by alexus37** [comment] 2019-11-06 16:17
So I investigate a bit more and found out that this occurs if you try to include the production build of react-google-streetview into a production build of another app. The issue is because of the double minification done by webpack. This is a bug in webpack minifier terser (see https://github.com/terser/terser/issues/308) and can be fixed by upgrading webpack to the newest version.

**Closed as completed by alexus37** 2019-11-06 16:17 UTC
